language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2

matrix:
    fast_finish: true

install:
    - composer selfupdate
    - composer update

script:
    - vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        recipients:
            - poisoncorpsee@gmail.com
        on_success: always
        on_failure: always
